### PR TITLE
Commit changes to Remoteness data and eda to reflect fix to mismatche…

### PR DESCRIPTION
**Pull request by Neil-Cunningham**
…d SA4 name values e.g. "Hobart" changed to "Greater Hobart"

### CODE REVIEW

**Review by Neil-Cunningham — COMMENTED** [review]
Hey Hnin/Ana - I looked at this file and the conflcits seem OK - please approve

**Review by AnaMJaimeR — APPROVED** [review]
Approved

**Comment by Neil-Cunningham** [comment]
Hi Ana - The below message seems to indicate that even though we worked together to resolve and approve thes conflicts - for some reason they continue to be rejected.  I have decided to do a complete wipe of all my Git repos and folders and files (after doing a backup) and try and re-establish everyhting clean - so I suggest we "Close" this Pull Request to try and clear it away so it doesn't confuse things going forward - what do you think?

**Comment by Neil-Cunningham** [comment]
AS agreed - we'll close this pull request as part of my re-fresh and re-start with Git

**Pull request closed without merging**
